### ISSUE TITLE
Why not BSD 2-Clause License?

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-common-settings#2]
BSD 2-Clause License is what everyone uses these days. Is there a special reason it is not used here?

**Comment by pkgdemon** [comment]
It seemed like a good idea at the time.  Is there a reason BSD 3-Clause is bad?

**Comment by probonopd** [comment]
I don't have any issues with the contents of it, just see that FreeBSD uses 2-Clause and FuryBSD is FreeBSD, after all. So I think it would be more consistent, and simpler.

**Comment by pkgdemon** [comment]
I based mine off FreeNAS and some other projects.  The 3rd clause seemed reasonable.  I didn't see a reason not to have it.
